// <auto-generated />
namespace SportsEvents.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class EventsCommentsTablesCreated : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EventsCommentsTablesCreated));
        
        string IMigrationMetadata.Id
        {
            get { return "201707261845447_Events & Comments Tables Created"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
